# THIS IS A TEMPLATE PLEASE FILL IN DATA AND RENAME TO config.yaml
api:
  blizzard:
    client_id: your_id_here
    client_secret: your_secret_here

characters:
  region:
    realm0:
      - character0
      - character1
    reaml1:
      - character2
      - character3

database:
  sqlite:///altaudit.db

server:
  localhost:/var/www/html
