{'primary': [
    {'id': 2486, 'name': 'Kul Tiran Enchanting', 'icon': 'trade_engraving', 'rank': 175, 'max': 150},
    {'id': 2487, 'name': 'Legion Enchanting', 'icon': 'trade_engraving', 'rank': 100, 'max': 100},
    {'id': 2488, 'name': 'Draenor Enchanting', 'icon': 'trade_engraving', 'rank': 100, 'max': 100},
    {'id': 2489, 'name': 'Pandaria Enchanting', 'icon': 'trade_engraving', 'rank': 75, 'max': 75},
    {'id': 2491, 'name': 'Cataclysm Enchanting', 'icon': 'trade_engraving', 'rank': 75, 'max': 75},
    {'id': 2492, 'name': 'Northrend Enchanting', 'icon': 'trade_engraving', 'rank': 75, 'max': 75},
    {'id': 2493, 'name': 'Outland Enchanting', 'icon': 'trade_engraving', 'rank': 75, 'max': 75},
    {'id': 197, 'name': 'Tailoring', 'icon': 'trade_tailoring', 'rank': 300, 'max': 300},
    {'id': 333, 'name': 'Enchanting', 'icon': 'trade_engraving', 'rank': 300, 'max': 300},
    {'id': 2533, 'name': 'Kul Tiran Tailoring', 'icon': 'trade_tailoring', 'rank': 175, 'max': 150},
    {'id': 2534, 'name': 'Legion Tailoring', 'icon': 'trade_tailoring', 'rank': 100, 'max': 100},
    {'id': 2535, 'name': 'Draenor Tailoring', 'icon': 'trade_tailoring', 'rank': 100, 'max': 100},
    {'id': 2536, 'name': 'Pandaria Tailoring', 'icon': 'trade_tailoring', 'rank': 75, 'max': 75},
    {'id': 2537, 'name': 'Cataclysm Tailoring', 'icon': 'trade_tailoring', 'rank': 75, 'max': 75},
    {'id': 2538, 'name': 'Northrend Tailoring', 'icon': 'trade_tailoring', 'rank': 75, 'max': 75},
    {'id': 2539, 'name': 'Outland Tailoring', 'icon': 'trade_tailoring', 'rank': 75, 'max': 75}],
'secondary': [
    {'id': 2585, 'name': 'Kul Tiran Fishing', 'icon': 'trade_fishing', 'rank': 65, 'max': 150},
    {'id': 794, 'name': 'Archaeology', 'icon': 'trade_archaeology', 'rank': 600, 'max': 950},
    {'id': 2586, 'name': 'Legion Fishing', 'icon': 'trade_fishing', 'rank': 1, 'max': 100},
    {'id': 2587, 'name': 'Draenor Fishing', 'icon': 'trade_fishing', 'rank': 1, 'max': 100},
    {'id': 2588, 'name': 'Pandaria Fishing', 'icon': 'trade_fishing', 'rank': 75, 'max': 75},
    {'id': 2589, 'name': 'Cataclysm Fishing', 'icon': 'trade_fishing', 'rank': 75, 'max': 75},
    {'id': 2590, 'name': 'Northrend Fishing', 'icon': 'trade_fishing', 'rank': 75, 'max': 75},
    {'id': 2591, 'name': 'Outland Fishing', 'icon': 'trade_fishing', 'rank': 75, 'max': 75},
    {'id': 185, 'name': 'Cooking', 'icon': 'inv_misc_food_15', 'rank': 300, 'max': 300},
    {'id': 356, 'name': 'Fishing', 'icon': 'trade_fishing', 'rank': 300, 'max': 300},
    {'id': 2541, 'name': 'Kul Tiran Cooking', 'icon': 'inv_misc_food_15', 'rank': 175, 'max': 150},
    {'id': 2542, 'name': 'Legion Cooking', 'icon': 'inv_misc_food_15', 'rank': 1, 'max': 100},
    {'id': 2543, 'name': 'Draenor Cooking', 'icon': 'inv_misc_food_15', 'rank': 5, 'max': 100},
    {'id': 2544, 'name': 'Pandaria Cooking', 'icon': 'inv_misc_food_15', 'rank': 75, 'max': 75},
    {'id': 2545, 'name': 'Cataclysm Cooking', 'icon': 'inv_misc_food_15', 'rank': 75, 'max': 75},
    {'id': 2546, 'name': 'Northrend Cooking', 'icon': 'inv_misc_food_15', 'rank': 75, 'max': 75},
    {'id': 2547, 'name': 'Outland Cooking', 'icon': 'inv_misc_food_15', 'rank': 75, 'max': 75}]}
