"""Changes for migration to Profile API

Revision ID: 0a31ea25122a
Revises: cc67fc067add
Create Date: 2020-02-20 11:47:23.107456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a31ea25122a'
down_revision = 'cc67fc067add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azerite_percentage', sa.Float(), nullable=True))
        batch_op.alter_column('finger1_enchant_description', new_column_name='finger_1_enchant_description')
        batch_op.alter_column('finger1_enchant_id', new_column_name='finger_1_enchant_id')
        batch_op.alter_column('finger1_enchant_name', new_column_name='finger_1_enchant_name')
        batch_op.alter_column('finger1_enchant_quality', new_column_name='finger_1_enchant_quality')
        batch_op.alter_column('finger1_id', new_column_name='finger_1_id')
        batch_op.alter_column('finger1_itemLevel', new_column_name='finger_1_itemLevel')
        batch_op.alter_column('finger1_name', new_column_name='finger_1_name')
        batch_op.alter_column('finger1_quality', new_column_name='finger_1_quality')
        batch_op.alter_column('finger2_enchant_description', new_column_name='finger_2_enchant_description')
        batch_op.alter_column('finger2_enchant_id', new_column_name='finger_2_enchant_id')
        batch_op.alter_column('finger2_enchant_name', new_column_name='finger_2_enchant_name')
        batch_op.alter_column('finger2_enchant_quality', new_column_name='finger_2_enchant_quality')
        batch_op.alter_column('finger2_id', new_column_name='finger_2_id')
        batch_op.alter_column('finger2_itemLevel', new_column_name='finger_2_itemLevel')
        batch_op.alter_column('finger2_name', new_column_name='finger_2_name')
        batch_op.alter_column('finger2_quality', new_column_name='finger_2_quality')
        batch_op.alter_column('mainHand_enchant_description', new_column_name='main_hand_enchant_description')
        batch_op.alter_column('mainHand_enchant_id', new_column_name='main_hand_enchant_id')
        batch_op.alter_column('mainHand_enchant_name', new_column_name='main_hand_enchant_name')
        batch_op.alter_column('mainHand_enchant_quality', new_column_name='main_hand_enchant_quality')
        batch_op.alter_column('mainHand_id', new_column_name='main_hand_id')
        batch_op.alter_column('mainHand_itemLevel', new_column_name='main_hand_itemLevel')
        batch_op.alter_column('mainHand_name', new_column_name='main_hand_name')
        batch_op.alter_column('mainHand_quality', new_column_name='main_hand_quality')
        batch_op.alter_column('offHand_enchant_description', new_column_name='off_hand_enchant_description')
        batch_op.alter_column('offHand_enchant_id', new_column_name='off_hand_enchant_id')
        batch_op.alter_column('offHand_enchant_name', new_column_name='off_hand_enchant_name')
        batch_op.alter_column('offHand_enchant_quality', new_column_name='off_hand_enchant_quality')
        batch_op.alter_column('offHand_id', new_column_name='off_hand_id')
        batch_op.alter_column('offHand_itemLevel', new_column_name='off_hand_itemLevel')
        batch_op.alter_column('offHand_name', new_column_name='off_hand_name')
        batch_op.alter_column('offHand_quality', new_column_name='off_hand_quality')
        batch_op.alter_column('trinket1_id', new_column_name='trinket_1_id')
        batch_op.alter_column('trinket1_itemLevel', new_column_name='trinket_1_itemLevel')
        batch_op.alter_column('trinket1_name', new_column_name='trinket_1_name')
        batch_op.alter_column('trinket1_quality', new_column_name='trinket_1_quality')
        batch_op.alter_column('trinket2_id', new_column_name='trinket_2_id')
        batch_op.alter_column('trinket2_itemLevel', new_column_name='trinket_2_itemLevel')
        batch_op.alter_column('trinket2_name', new_column_name='trinket_2_name')
        batch_op.alter_column('trinket2_quality', new_column_name='trinket_2_quality')
        batch_op.drop_column('chest_icon')
        batch_op.drop_column('waist_icon')
        batch_op.drop_column('feet_icon')
        batch_op.drop_column('trinket1_icon')
        batch_op.drop_column('legs_icon')
        batch_op.drop_column('offHand_icon')
        batch_op.drop_column('finger2_icon')
        batch_op.drop_column('mainHand_icon')
        batch_op.drop_column('neck_icon')
        batch_op.drop_column('head_icon')
        batch_op.drop_column('wrist_icon')
        batch_op.drop_column('back_icon')
        batch_op.drop_column('finger1_icon')
        batch_op.drop_column('trinket2_icon')
        batch_op.drop_column('shoulder_icon')
        batch_op.drop_column('hands_icon')
        batch_op.drop_column('azerite_experience')
        batch_op.drop_column('azerite_experience_remaining')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azerite_experience_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('azerite_experience', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hands_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('trinket2_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('finger1_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('back_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('wrist_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('head_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('neck_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mainHand_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('finger2_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('offHand_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('legs_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('trinket1_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('feet_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('waist_icon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('chest_icon', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('trinket_2_quality', new_column_name='trinket2_quality')
        batch_op.alter_column('trinket_2_name', new_column_name='trinket2_name')
        batch_op.alter_column('trinket_2_itemLevel', new_column_name='trinket2_itemLevel')
        batch_op.alter_column('trinket_2_id', new_column_name='trinket2_id')
        batch_op.alter_column('trinket_1_quality', new_column_name='trinket1_quality')
        batch_op.alter_column('trinket_1_name', new_column_name='trinket1_name')
        batch_op.alter_column('trinket_1_itemLevel', new_column_name='trinket1_itemLevel')
        batch_op.alter_column('trinket_1_id', new_column_name='trinket1_id')
        batch_op.alter_column('off_hand_quality', new_column_name='offHand_quality')
        batch_op.alter_column('off_hand_name', new_column_name='offHand_name')
        batch_op.alter_column('off_hand_itemLevel', new_column_name='offHand_itemLevel')
        batch_op.alter_column('off_hand_id', new_column_name='offHand_id')
        batch_op.alter_column('off_hand_enchant_quality', new_column_name='offHand_enchant_quality')
        batch_op.alter_column('off_hand_enchant_name', new_column_name='offHand_enchant_name')
        batch_op.alter_column('off_hand_enchant_id', new_column_name='offHand_enchant_id')
        batch_op.alter_column('off_hand_enchant_description', new_column_name='offHand_enchant_description')
        batch_op.alter_column('main_hand_quality', new_column_name='mainHand_quality')
        batch_op.alter_column('main_hand_name', new_column_name='mainHand_name')
        batch_op.alter_column('main_hand_itemLevel', new_column_name='mainHand_itemLevel')
        batch_op.alter_column('main_hand_id', new_column_name='mainHand_id')
        batch_op.alter_column('main_hand_enchant_quality', new_column_name='mainHand_enchant_quality')
        batch_op.alter_column('main_hand_enchant_name', new_column_name='mainHand_enchant_name')
        batch_op.alter_column('main_hand_enchant_id', new_column_name='mainHand_enchant_id')
        batch_op.alter_column('main_hand_enchant_description', new_column_name='mainHand_enchant_description')
        batch_op.alter_column('finger_2_quality', new_column_name='finger2_quality')
        batch_op.alter_column('finger_2_name', new_column_name='finger2_name')
        batch_op.alter_column('finger_2_itemLevel', new_column_name='finger2_itemLevel')
        batch_op.alter_column('finger_2_id', new_column_name='finger2_id')
        batch_op.alter_column('finger_2_enchant_quality', new_column_name='finger2_enchant_quality')
        batch_op.alter_column('finger_2_enchant_name', new_column_name='finger2_enchant_name')
        batch_op.alter_column('finger_2_enchant_id', new_column_name='finger2_enchant_id')
        batch_op.alter_column('finger_2_enchant_description', new_column_name='finger2_enchant_description')
        batch_op.alter_column('finger_1_quality', new_column_name='finger1_quality')
        batch_op.alter_column('finger_1_name', new_column_name='finger1_name')
        batch_op.alter_column('finger_1_itemLevel', new_column_name='finger1_itemLevel')
        batch_op.alter_column('finger_1_id', new_column_name='finger1_id')
        batch_op.alter_column('finger_1_enchant_quality', new_column_name='finger1_enchant_quality')
        batch_op.alter_column('finger_1_enchant_name', new_column_name='finger1_enchant_name')
        batch_op.alter_column('finger_1_enchant_id', new_column_name='finger1_enchant_id')
        batch_op.alter_column('finger_1_enchant_description', new_column_name='finger1_enchant_description')
        batch_op.drop_column('azerite_percentage')

    # ### end Alembic commands ###
