"""Added missing gem slot slots to table

Revision ID: 46359a97caea
Revises: 3e346529baa3
Create Date: 2020-02-27 17:29:25.522646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46359a97caea'
down_revision = '3e346529baa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empty_socket_slots', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('empty_socket_slots')

    # ### end Alembic commands ###
